### PR TITLE
Fix for loading system snapshots

### PR DESCRIPTION
**Pull request by dubs999**
Issue identified earlier in the day around cluster snapshots not being deserialized correctly.

https://github.com/AkkaNetContrib/Akka.Persistence.PostgreSql/issues/57

Deserialization style copied from (working) journal store.

https://github.com/AkkaNetContrib/Akka.Persistence.PostgreSql/blob/dev/src/Akka.Persistence.PostgreSql/Journal/PostgreSqlQueryExecutor.cs#L158:L165

### CODE REVIEW

**Comment by Horusiath** [comment]
Thanks for active help in fixing this issue 👍 Shouldn't we have a test for it? Have you checked if this works?

**Comment by dubs999** [comment]
I just took a look at the `Akka.Persistence.TCK` specs and I cant see any tests related to sharding level events. I would help contribute some tests here but unfortunately I don't really know enough about how the framework works.

Although it's a basic test, I have run this up locally in my own project and witnessed snapshots being taken and reloaded after multiple restarts.

I can update the PR to the latest `1.3.9` Akka build and re-test?

**Comment by Aaronontheweb** [comment]
> I can update the PR to the latest 1.3.9 Akka build and re-test?

That'd be a great idea @dubs999

**Comment by dubs999** [comment]
Hey guys, I've manually tested the application using the `1.3.9` Akka release, and the `1.3.9-beta68` Sharding libraries and everything behaved as expected.

I'm not familiar with the error in the TC build. Potentially a transient one? Could someone help me look into that.

Cheers, Dan

**Comment by Aaronontheweb** [comment]
@dubs999 so the issue here is that the latest version of the Postgres driver targets .NET Standard 2.0. This library currently targets .NET Standard 1.6. We'd need to either roll back to an older driver version or bump this project to .NET Standard 2.0 to fix it.

https://github.com/AkkaNetContrib/Akka.Persistence.PostgreSql/blob/cb68796438719776cc44a46cd3dc75d461a9b417/src/Akka.Persistence.PostgreSql/Akka.Persistence.PostgreSql.csproj#L7

We already do dual release under .NET 4.5 and .NET Standard 1.6, so if we bumped to .NET Standard 2.0 for this package virtually no one would be affected - we did a survey of all Akka.NET users and we had 0 respondents say they use .NET Core 1.*. All of them jumped straight to 2.0 when it came out. So I think that'd be the better solution rather than trying to use an older version of the driver.

**Comment by dubs999** [comment]
I've upgraded the version of netstandard but the application still fails to restore which is odd seeing as this is how I've been running my testing locally. Any other suggestions? I can downgrade the version of `Npgsql` but that feels like a step in the wrong direction.

**Comment by Aaronontheweb** [comment]
@dubs999 let me check to see if there's something goofy going on with our build scripts

**Comment by Aaronontheweb** [comment]
Yeah it's a minor issue with the build script - fixed this one a few times in other projects this summer. I'll add a commit for it.

**Comment by Aaronontheweb** [comment]
So bad news - going to have to roll back the driver and .NET Standard version. Reason being is that we have some polyfills left over from .NET Standard 1.* which conflict with types by the same name in .NET Standard 2.0. Akka.NET will need to be upgraded to .NET Standard 2.0 first to resolve this, which we expect to have done as part of our 1.4.0 release. Sorry for the trouble.

**Comment by Aaronontheweb** [comment]
Closed via #60

**Pull request closed without merging**
